#!/usr/bin/env bash
# sets the wallpaper to the bing wallpaper of the day
# requires curl and jq
# works with gnome (gsettings) and kde (plasma-apply-wallpaperimage)

# Location for wallpapers to be saved
if [ -z "$BING_WALLPAPER_LOCATION" ]; then
    PICTURES_DIR="$HOME/Pictures"
    if command -v xdg-user-dir &>/dev/null; then
        PICTURES_DIR=$(xdg-user-dir PICTURES)
    fi

    BING_WALLPAPER_LOCATION="$PICTURES_DIR/bing-wallpaper"
fi

echo "Storing wallpapers in $BING_WALLPAPER_LOCATION"

if ! [ -d "$BING_WALLPAPER_LOCATION" ]; then
    mkdir -p "$BING_WALLPAPER_LOCATION"
fi

# Number of days to keep wallpapers. -1 to disable
if [ -z "$BING_WALLPAPER_KEEP_FOR" ]; then
    BING_WALLPAPER_KEEP_FOR=7
fi

mkdir -p "$BING_WALLPAPER_LOCATION"

RESPONSE=$(curl "https://www.bing.com/HPImageArchive.aspx?format=js&idx=0&n=1&mkt=en-US")
TIMESTAMP=$(echo "$RESPONSE" | jq -r ".images[0].startdate")
FILENAME="$BING_WALLPAPER_LOCATION/$TIMESTAMP.jpg"

# only download and set wallpaper if not already downloaded
if ! [ -f "$FILENAME" ]; then
    IMAGE_URL_BASE=$(echo "$RESPONSE" | jq -r ".images[0].url")

    curl "https://bing.com$IMAGE_URL_BASE" -o "$FILENAME"

    echo "Saving $FILENAME"
fi

# apply wallpaper on GNOME
# apply as both dark and light wallpaper
if command -v gsettings &>/dev/null; then
    echo "Applying wallpaper (GNOME)"
    gsettings set org.gnome.desktop.background picture-uri "file://$FILENAME"
    gsettings set org.gnome.desktop.background picture-uri-dark "file://$FILENAME"
fi

# apply wallpaper on KDE
if command -v plasma-apply-wallpaperimage &>/dev/null; then
    echo "Applying wallpaper (KDE)"
    plasma-apply-wallpaperimage "$FILENAME"
fi

if [ "$BING_WALLPAPER_KEEP_FOR" -ge 0 ]; then
    echo "Deleting wallpapers older than $BING_WALLPAPER_KEEP_FOR days"
    find "$BING_WALLPAPER_LOCATION" -name "*.jpg" -type f -mtime "+$BING_WALLPAPER_KEEP_FOR" -exec rm {} \;
fi
